//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int SeatId { get; set; }
        public int UserId { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Sessions Sessions { get; set; }
        public virtual TicketStatuses TicketStatuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
